name: Build Image

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build:
    name: ðŸ§± Build Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image
        run: |
            docker build -t meu-app-builder -f api/Dockerfile.build .
            docker build -t meu-app -f api/Dockerfile.run .
    # - name: Push Docker Image to Docker Hub
    #   env:
    #       DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
    #       DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    # run: |
    #     echo $DOCKER_HUB_ACCESS_TOKEN | docker login -u $DOCKER_HUB_USERNAME --password-stdin
    #     docker tag meu-app-runner $DOCKER_HUB_USERNAME/meu-app:latest
    #     docker push $DOCKER_HUB_USERNAME/meu-app:latest