name: Slack Notification - PR Opened

on:
  pull_request:
    types: [opened]

jobs:
  send_notification_opened:
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack Notification - PR Opened
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL:
          SLACK_MESSAGE: "Pull Request opened by ${{ github.actor }} in ${{ github.repository }}:${{ github.ref }}\n\nTitle: ${{ github.event.pull_request.title }}\n\nREVIEW URL: ${{ github.event.pull_request.html_url }}/files"